DROP TABLE COMMUNITYS;


CREATE TABLE COMMUNITY (
COMM_NUM NUMBER,
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(2048) NOT NULL,
HITS VARCHAR2(2048),
RECOM VARCHAR2(2048),
COM_DATE DATE,
MEMBER_ID VARCHAR(100)
); 

CREATE TABLE COMMUNITYS (
COMM_NUM NUMBER,
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(2048) NOT NULL,
COM_DATE DATE,
MEMBER_ID VARCHAR(100)
);

CREATE SEQUENCE COMM_NUM START WITH 1 INCREMENT BY 1;
DROP SEQUENCE COMM_NUM;

SELECT COMM_NUM.CURRVAL FROM COMMUNITYS; --해당 시퀀스 값 조회
SELECT * FROM USER_SEQUENCES;

INSERT INTO COMMUNITYS VALUES (MSG_NUM.NEXTVAL, 'sdf', 'ewe', SYSDATE)


SELECT * FROM COMMUNITYS;