DROP TABLE COMMUNITYS;


CREATE TABLE COMMUNITY (
COMM_NUM NUMBER,
TITLE VARCHAR2(100),
CONTENT VARCHAR2(2048),
MEMBER_ID VARCHAR2(50),
HITS VARCHAR2(2048),
RECOM VARCHAR2(2048),
COM_DATE DATE
); 

CREATE TABLE COMMUNITYS (
COMM_NUM NUMBER,(100
TITLE VARCHAR2) NOT NULL,
CONTENT VARCHAR2(2048) NOT NULL,
COM_DATE DATE
);

CREATE SEQUENCE COMM_NUM START WITH 1 INCREMENT BY 1;

INSERT INTO COMMUNITYS VALUES (MSG_NUM.NEXTVAL, 'sdf', 'ewe', SYSDATE)


SELECT * FROM COMMUNITYS;